const scholarshipImages={students:'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=900&q=80',study:'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=900&q=80',laptop:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80',library:'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=900&q=80',engineering:'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=900&q=80',medicine:'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=900&q=80'};
const scholarships=[
{id:1,title:'Chevening Scholarships',org:'UK Foreign, Commonwealth & Development Office',level:"Master's",field:'All subjects',country:'United Kingdom',funding:'Fully funded',award:'Full financial support',deadline:'6 Oct 2026',image:scholarshipImages.students,description:'The UK government’s global scholarship programme supports eligible applicants to pursue a one-year taught master’s degree at a UK university. The 2027–28 application cycle is open from 4 August to 6 October 2026.',url:'https://www.chevening.org/scholarships/application-timeline/'},
{id:2,title:'Commonwealth Shared Scholarships',org:'Commonwealth Scholarship Commission in the UK',level:"Master's",field:'Development-related subjects',country:'United Kingdom',funding:'Fully funded',award:'Fees + airfare + stipend',deadline:'Varies by annual cycle',image:scholarshipImages.laptop,description:'Scholarships for candidates from eligible low- and middle-income Commonwealth countries to undertake selected one-year taught Master’s courses at participating UK universities. Funding can include tuition, airfare and a living allowance.',url:'https://cscuk.fcdo.gov.uk/scholarships/commonwealth-shared-scholarships/'},
{id:3,title:'Commonwealth Master’s Scholarships',org:'Commonwealth Scholarship Commission in the UK',level:"Master's",field:'Development-related subjects',country:'United Kingdom',funding:'Fully funded',award:'Tuition + airfare + living allowance',deadline:'Annual cycle',image:scholarshipImages.study,description:'UK government-funded Master’s scholarships for eligible citizens of low- and middle-income Commonwealth countries. Candidates are normally nominated through an eligible nominating agency.',url:'https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships/'},
{id:4,title:'Gates Cambridge Scholarship',org:'University of Cambridge',level:"Master's / PhD",field:'Eligible postgraduate subjects',country:'United Kingdom',funding:'Fully funded',award:'Full cost of study + maintenance',deadline:'Course/funding deadline varies',image:scholarshipImages.library,description:'A postgraduate scholarship at the University of Cambridge for applicants from outside the UK. Eligible full-time postgraduate study can receive funding covering the main costs of study and maintenance.',url:'https://www.gatescambridge.org/scholarships/'},
{id:5,title:'Clarendon Fund Scholarships',org:'University of Oxford',level:"Master's / DPhil",field:'All subjects',country:'United Kingdom',funding:'Fully funded',award:'Full fees + living grant',deadline:'December/January course deadline',image:scholarshipImages.study,description:'Oxford’s Clarendon Fund offers more than 200 new fully funded scholarships each year. There are no nationality or subject restrictions for eligible new Master’s and DPhil applicants who meet the relevant course deadline.',url:'https://www.ox.ac.uk/admissions/graduate/fees-and-funding/funding/clarendon'},
{id:6,title:'Rhodes Scholarship',org:'Rhodes Trust — University of Oxford',level:'Postgraduate',field:'Eligible full-time postgraduate study',country:'United Kingdom',funding:'Fully funded',award:'Fees + stipend',deadline:'Varies by constituency',image:scholarshipImages.engineering,description:'A postgraduate scholarship supporting students from eligible constituencies to study at the University of Oxford. Application dates and eligibility vary by constituency.',url:'https://www.rhodeshouse.ox.ac.uk/scholarships/the-rhodes-scholarship/'},
{id:7,title:'GREAT Scholarships',org:'British Council & participating UK universities',level:"Master's",field:'Multiple subjects',country:'United Kingdom',funding:'Partially funded',award:'At least £10,000 tuition support',deadline:'Varies by university',image:scholarshipImages.laptop,description:'GREAT Scholarships offer at least £10,000 towards tuition fees for eligible one-year taught postgraduate courses at participating UK universities. Available countries, courses and deadlines vary.',url:'https://study-uk.britishcouncil.org/scholarships-funding/great-scholarships'},
{id:8,title:'President’s PhD Scholarships',org:'Imperial College London',level:'PhD',field:'Multiple research disciplines',country:'United Kingdom',funding:'Fully funded',award:'Full tuition + stipend + research fund',deadline:'2 Nov 2026 / 11 Jan 2027 / 1 Mar 2027',image:scholarshipImages.engineering,description:'Imperial College London’s President’s PhD Scholarship provides full tuition funding, a stipend and a consumables fund. The scheme is open to talented candidates from the UK and worldwide with no nationality restriction.',url:'https://www.imperial.ac.uk/study/fees-and-funding/postgraduate-doctoral/grants-scholarships/presidents-phd/'},
{id:9,title:'UCL Global Master’s Scholarship',org:'University College London',level:"Master's",field:'All eligible postgraduate taught courses',country:'United Kingdom',funding:'Partially funded',award:'£15,000 for one year',deadline:'Expected early May 2027',image:scholarshipImages.students,description:'UCL’s Global Master’s Scholarship supports international students from lower-income backgrounds undertaking eligible full-time Master’s study at UCL. The award is worth £15,000 for one year.',url:'https://www.ucl.ac.uk/scholarships/ucl-global-masters-scholarship'},
{id:10,title:'University of Edinburgh Mastercard Foundation Scholars Program',org:'University of Edinburgh',level:"Master's",field:'Selected postgraduate programmes',country:'United Kingdom',funding:'Fully funded',award:'Tuition + living and study support',deadline:'19 Nov 2026',image:scholarshipImages.medicine,description:'The Mastercard Foundation Scholars Program at the University of Edinburgh supports eligible scholars through postgraduate study. For the 2027/28 cycle, the scholarship application main deadline is 19 November 2026 at 5pm UK time after completing the required information-session process.',url:'https://edinburgh-global.ed.ac.uk/mastercard-foundation-scholars-program/apply-for-a-scholarship/how-to-apply'}
]
function qs(s){return document.querySelector(s)}
function toast(msg){const el=qs('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function getUser(){try{return JSON.parse(localStorage.getItem('genuine_scholars_user'))}catch{return null}}
function mountSiteHeader(){
 const host=document.getElementById('siteHeader');
 if(!host)return;
 host.innerHTML=`<div class="topbar"><div class="container"><span>Genuine Scholars — Scholarship discovery platform</span><span>UK scholarship opportunities</span></div></div><header class="navbar"><div class="container nav-inner"><a class="logo" href="index.html"><img src="images/genuine-scholars-logo.png" alt="Genuine Scholars" class="site-logo"></a><button class="mobile-toggle" aria-label="Open menu">☰</button><nav class="nav-links"><a href="index.html">Home</a><a href="scholarships.html">Scholarships</a><a href="how-it-works.html">How it works</a><a href="ielts.html">IELTS Test</a><a href="about.html">About</a><a href="faq.html">FAQ</a><a href="contact.html">Contact</a></nav><div class="nav-actions"><a class="btn btn-primary btn-sm" href="contact.html">Contact Us</a></div></div></header>`;
}
function updateAuthUI(){const user=getUser();document.querySelectorAll('[data-auth="user"]').forEach(x=>x.classList.toggle('hidden',!user));document.querySelectorAll('[data-auth="guest"]').forEach(x=>x.classList.toggle('hidden',!!user));document.querySelectorAll('[data-user-name]').forEach(x=>x.textContent=user?.name||user?.organization||'Student');document.querySelectorAll('[data-logout]').forEach(x=>x.onclick=()=>{localStorage.removeItem('genuine_scholars_user');location.href='index.html'})}
document.addEventListener('DOMContentLoaded',()=>{mountSiteHeader();updateAuthUI();const t=qs('#homeSearch');if(t){t.addEventListener('keydown',e=>{if(e.key==='Enter')location.href='scholarships.html?q='+encodeURIComponent(t.value)})}const toggle=qs('.mobile-toggle');if(toggle)toggle.onclick=()=>qs('.nav-inner').classList.toggle('menu-open');document.querySelectorAll('.faq-q').forEach(q=>q.onclick=()=>q.parentElement.classList.toggle('open'));const featured=qs('[data-scholarships]');if(featured){const limit=Number(featured.dataset.limit||6);featured.innerHTML=scholarships.slice(0,limit).map(cardHTML).join('')}});
function cardHTML(s){return `<article class="card scholar-card"><img src="${s.image}" alt="Students studying"><div class="scholar-body"><div class="tag-row"><span class="tag">${s.level}</span><span class="tag">${s.funding}</span></div><h3>${s.title}</h3><p>${s.org}</p><div class="meta"><span>Field<strong>${s.field}</strong></span><span>Award<strong>${s.award}</strong></span><span>Location<strong>${s.country}</strong></span><span>Deadline<strong>${s.deadline}</strong></span></div><a class="btn btn-outline btn-sm" href="scholarship-details.html?id=${s.id}">View scholarship</a></div></article>`}
window.scholarships=scholarships;window.scholarshipImages=scholarshipImages;window.cardHTML=cardHTML;window.toast=toast;window.getUser=getUser;
